# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='reservado',
        ),
        migrations.AddField(
            model_name='copialibro',
            name='reservado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
