# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0002_auto_20170420_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
