# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0003_reservacion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='cod_libro',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
