# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0004_reservacion_cod_libro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='plazo_dias',
        ),
        migrations.AddField(
            model_name='categoria',
            name='plazo_dias',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
