# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0006_remove_categoria_plazo_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='plazo_dias',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
