# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0008_auto_20170519_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copialibro',
            name='prestado',
        ),
        migrations.AddField(
            model_name='reservacion',
            name='fecha_prestamo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='prestado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='fecha_entrega',
            field=models.DateTimeField(null=True),
        ),
    ]
