# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0009_auto_20170522_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='plazo_dias',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
