# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0010_reservacion_plazo_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_libro', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_reservacion', models.DateTimeField()),
                ('fecha_prestamo', models.DateTimeField(null=True)),
                ('fecha_entrega', models.DateTimeField(null=True)),
                ('comentario', models.CharField(max_length=300, null=True)),
                ('prestado', models.BooleanField()),
                ('plazo_dias', models.IntegerField()),
                ('cod_copia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.CopiaLibro')),
                ('numero_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.Perfil')),
            ],
        ),
    ]
