# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0011_prestamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_reservacion',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='prestado',
        ),
    ]
