# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0012_auto_20170528_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='comentario',
        ),
    ]
