# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0013_remove_prestamo_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='numPrestamos',
            field=models.IntegerField(null=True),
        ),
    ]
