# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('plazo_dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CopiaLibro',
            fields=[
                ('cod_copia', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('cod_libro', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('portada', models.ImageField(upload_to='media/portada')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Area')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Autor')),
                ('edicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Edicion')),
                ('editorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='security.Editorial')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('numero_cuenta', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservado', models.BooleanField()),
                ('fecha_reservacion', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField()),
                ('comentario', models.CharField(max_length=300, null=True)),
                ('cod_copia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.CopiaLibro')),
                ('numero_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Perfil')),
            ],
        ),
        migrations.AddField(
            model_name='copialibro',
            name='cod_libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Libro'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='numero_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Perfil'),
        ),
    ]
