# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='numero_cuenta',
        ),
        migrations.RemoveField(
            model_name='copialibro',
            name='cod_libro',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='area',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='edicion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='cod_copia',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='numero_cuenta',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='CopiaLibro',
        ),
        migrations.DeleteModel(
            name='Edicion',
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
        migrations.DeleteModel(
            name='Idioma',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Reservacion',
        ),
    ]
